# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/configuration/all/
# -------------------------------------------------------------------------------------
# website title (言語別に上書きされる)
title = "homelab blog"

# Hostname (and path) to the root
baseURL = "https://utibori-jp.github.io/homelab-blog/"

# theme list
# theme = ["FixIt"] # enable in your site config file

# determines default content language
defaultContentLanguage = "ja"

# whether to include Chinese/Japanese/Korean
hasCJKLanguage = true

# copyright description used only for seo schema
copyright = ""

# whether to use robots.txt
enableRobotsTXT = true

# whether to use git commit log
enableGitInfo = true

# whether to use emoji code
enableEmoji = true

# the main sections of a site
mainSections = ["posts"]

# -------------------------------------------------------------------------------------
# Language Configuration
# -------------------------------------------------------------------------------------
[languages]
  [languages.ja]
    weight = 1
    languageCode = "ja-JP"
    languageName = "日本語"
    title = "homelab blog"
    [languages.ja.params]
      description = "自宅サーバ運用の記録"
  [languages.en]
    weight = 2
    languageCode = "en"
    languageName = "English"
    title = "homelab blog"
    [languages.en.params]
      description = "Notes on operating a home server"
