description = "自宅サーバー運用の記録"
keywords = ["homelab", "k3s", "ArgoCD", "GitOps", "Kubernetes"]

[author]
  name = "utibori-jp"
  email = ""
  link = "https://github.com/utibori-jp"
  avatar = ""

[app]
  title = "homelab blog"

[header]
  [header.title]
    logo = ""

[home]
  [home.profile]
    enable = true

[customPartials]
  head = [
    "inject/fixit-docs-bookmark.html",
  ]
